### ISSUE TITLE
Once again won't start

### ISSUE THREAD

**Issue by TrainDoesGames** [killpowa/Twickt-Launcher#1220]
**Describe the bug**
The GDLauncer will once again refuse to start and is stuck at loading screen after a recent update

**To Reproduce**
Start launcher

**Expected behavior**
To get the modpack overview

**Possible solutions**
Not known

**Screenshots**

**Operating System:**
- OS: Windows
- Version: 10

**Additional context**

**Comment by DwarfDolphin** [comment]
I too updated and cannot get it to open (again). 
This is so sad Alexa play Haggstrom by C418.

**Comment by c-sig** [comment]
Can you post a screenshot of the console?

**Comment by TrainDoesGames** [comment]
> Can you post a screenshot of the console?

![image](https://user-images.githubusercontent.com/78595978/147211235-187fa23d-ab22-463b-91f4-b66d310742d1.png)

I have hidden personal info, most of it is in AppData/roaming

**Comment by MotionBoy** [comment]
My GD launcher wouldn't launch either but redownloading the latest version and installing that fixed it for me, might help?

**Comment by TrainDoesGames** [comment]
> My GD launcher wouldn't launch either but redownloading the latest version and installing that fixed it for me, might help?

No fix for me

**Comment by TrainDoesGames** [comment]
> **Describe the bug** The GDLauncer will once again refuse to start and is stuck at loading screen after a recent update
> 
> **To Reproduce** Start launcher
> 
> **Expected behavior** To get the modpack overview
> 
> **Possible solutions** Not known
> 
> **Screenshots** If applicable, add screenshots to help explain your problem.
> 
> **Operating System:**
> 
> * OS: Windows
> * Version: 10
> 
> **Additional context** Add any other context about the problem here.

This issue is yet to be fixed

**Comment by Eskaan** [comment]
This issue should be fixed since yesterday - There was a wrong file on our webservices.
*I know it because I placed it there*
Maybe you will have for your cache to invalidate but I think since it was corrected yesterday it should be updated now.

**Comment by TrainDoesGames** [comment]
> This issue should be fixed since yesterday - There was a wrong file on our webservices. _I know it because I placed it there_ Maybe you will have for your cache to invalidate but I think since it was corrected yesterday it should be updated now.

this has not seemed to have fixed things locally, i have tried opening the developer console and refreshing there but no luck

EDIT: Side-note, I am on the beta release channel

2nd EDIT: Updating to the latest version did not fix things either, it's annoying but going back a version works just fine

**Comment by Eskaan** [comment]
Did anything in the console change?

**Comment by TrainDoesGames** [comment]
> Did anything in the console change?

after update or when going back a version?

Doesn't seem to have changed at a quick glance (update one)
![image](https://user-images.githubusercontent.com/78595978/147417881-0875c61c-2984-4b0b-8126-d71e702dbdef.png)

**Comment by Eskaan** [comment]
Okay.
Could you try disabling the cache (a checkbox in the network tab) And then press F5 or Ctrl+R? This should at least clear the Cannot read property error.

**Comment by TrainDoesGames** [comment]
> Okay. Could you try disabling the cache (a checkbox in the network tab) And then press F5 or Ctrl+R? This should at least clear the Cannot read property error.

It says I'm missing Java 8

Doing the Automatic setup for it now

**Comment by Eskaan** [comment]
Yeah it should do that. Now reinstall it

**Comment by TrainDoesGames** [comment]
> Yeah it should do that. Now reinstall it

It sent me straight to the mods menu, the screen i'm expected to see with all the modpacks, thanks for fixing this <3

**Comment by Eskaan** [comment]
Alright :)

**Comment by TrainDoesGames** [comment]
Also, do I just re-enable cache?

**Comment by Eskaan** [comment]
Sure

**Comment by TrainDoesGames** [comment]
Alright, getting errors but it is still at the modpacks screen, it seemed to have been fixed!

**Comment by Eskaan** [comment]
Are you Playing the „Reverse-Skies“  instance? Otherwise you can delete the folder it is trying to open named by the instabce

**Comment by Eskaan** [comment]
That should fix the problem whit the missing file error

**Comment by TrainDoesGames** [comment]
I have no Reverse-Skies instance, atleast none named that way

**Comment by Eskaan** [comment]
Yeah, maybe caused by a interrupted download.
You can delete the folder named Reverse-Skies

**Comment by TrainDoesGames** [comment]
Also the renaming of instances is a bit janky, cause when I tap save it just won't make the name change even after a relaunch of the GDL

**Comment by TrainDoesGames** [comment]
![image](https://user-images.githubusercontent.com/78595978/147419082-b69dc542-f3e1-4d27-8209-641079fedb18.png)

Also i doubt this is supposed to come up?

**Comment by TrainDoesGames** [comment]
It's for a Java Realms December.jpg or something

**Comment by Eskaan** [comment]
Yeah. Mad Mojang removed one of the entries. Will disappear whit time :)

**Comment by TrainDoesGames** [comment]
> Yeah. Mad Mojang removed one of the entries. Will disappear whit time :)

Alright, thanks for fixing all this though, I love the launcher
